---
title: "CSCI -- 220 Syllabus"
subtitle: "Spring 2026"
format: 
  pdf: 
    documentclass: article
    toc: false
    geometry: 
      - margin=1in
  #typst:
  #  toc: false
  #  number-sections: true
  #  brand-mode: light
  #  logo:
  #    width: 0in
---

# Instructor Information

**Instructor:** Tuck Williamson



## Contact



## Office Hours


| **Day**       | Office Hours                          |
|---------------|---------------------------------------|
| **Monday**    | By appointment only via Zoom         |
| **Tuesday**   | 11:30 am -12:30 pm<br>Class </br> **2 pm - 3 pm** |
| **Wednesday** | By appointment only via Zoom         |
| **Thursday**  | **11:30 am -12:30 pm**<br>***Class***<br>**2 pm - 3 pm** |
| **Friday**    | By appointment only via Zoom |
| **Saturday**  | By appointment only via Zoom |

: Office Hours

**11:30 am -12:30 pm**<br>***Class***<br>**2 pm - 3 pm**

## Background



# Course Information

## Key Dates


| **Date** | Event |
|----:|:-------------|
| **Wednesday, January 7** | Spring full semester and Express I classes begin. |
| **Tuesday, January 13** | Last day of Drop/Add for full semester classes. <br> Last day for students to submit a request to Audit or apply for a Pass/Not Pass grade option full semester classes. <br> Departmental Chairs' SZAAREG Deadline for Express I classes. |
| **Monday, January 19** | Martin Luther King, Jr. Holiday, observed. No classes. College closed. |
| **Saturday, January 24** | Storm Day Makeup (on campus instruction for PE Activity Courses, labs, studio, performance courses only; virtual instruction on these days for all other courses). (SD*) |
| **Sunday, January 25** | Storm Day Makeup (on campus instruction for PE Activity Courses, labs, studio, performance courses only; virtual instruction on these days for all other courses). (SD*) |
| **Saturday, February 7** | Storm Day Makeup (on campus instruction for PE Activity Courses, labs, studio, performance courses only; virtual instruction on these days for all other courses). (SD*) |
| **Sunday, March 1 - Sunday, March 8** | Spring Break. No classes. |
| **Friday, March 20** | Last day for students to withdraw with a status indicator of "W" from full semester classes. <br> Maymester and Summer Sessions registration begins for non-degree and visiting students. |
| **Wednesday, April 22** | Last day of full semester classes. Classes that normally meet on Monday only should meet on this date. |
| **Thursday, April 23** | Reading Day. Full semester and Express II grading open to faculty. |
| **Saturday, April 25 -- 3:30 p.m. - 5:30 p.m.** | ***FINAL EXAM FOR THIS CLASS** |
| **Tuesday, May 5** | Final grades for full semester and Express II classes available in MyPortal. |

: Important dates this semester {.striped}

::: {.callout-caution}

Note that our exam is on a ***Saturday***! 

Block this date/time off as I am not able to move it or make accommodations (except for college approved reasons).

:::


## Description

### Pre-requisites

### Co-requisite

## Goals

## Outcomes



# Grading

## Calculation

The following table details how your grade will be calculated.

| Grade Type | Weight |
|:----------|:---:|
| Final Exam | **30%** |
| Programs | **30%** |
| Tests (2)  | **20%** |
| Quizzes | **10%** |
| Zybooks Assignments | **10%** |

: Grading Weights {.striped .bordered fig-align="center"}

## Scale


