project:
  type: website
  output-dir: docs
website:
  google-analytics:
    tracking-id: "G-WRWNYTYD1G"
    storage: none
  announcement:
    icon: exclamation-circle
    dismissable: true
    content: "**Updated Office Hours - Jan 21<sup>st</sup>** - Please note that I have recent changes to my office hours.<br><i class=\"bi bi-thermometer-snow\"></i>&nbsp;I will still hold my office hours **via Zoom** during the *Inclement Weather* closure Jan 21-23. If you are working on HW1 and need help message me and I can help via Zoom."
    type: danger
    position: below-navbar