project:
  type: website
  output-dir: docs
  preview:
    port: 10001
    host: 41eb1c561fe6 #`uname -n`
    browser: false
website:
  google-analytics:
    tracking-id: "G-WRWNYTYD1G"
    storage: none
#  announcement:
#    icon: exclamation-circle
#    dismissable: true
#    content: "**Updated Office Hours - Jan 27<sup>st</sup>** - Please note that I have recent changes to my office hours."
#    type: danger
#    position: below-navbar