---
title: "CSCI 340 Operating Systems - Summer II 2025"
# ---- My Variables ----
office: "Harbor Walk East - HWEA Office #**311**"
#Change this below in the metadata too.
booklink: https://outlook.office.com/bookwithme/user/0a4ce8c8942f4df4a1c6249a52630d7a@g.cofc.edu?anonymous&ep=plink
#Change this below in the metadata too.
zoomlink: https://outlook.office.com/bookwithme/user/0a4ce8c8942f4df4a1c6249a52630d7a@g.cofc.edu/meetingtype/_TR502DM80G5OpzXWWKlMw2?anonymous&ep=mlink
# ---- End My Variables ----
#author: Tuck Williamson
date-modified: now
from: markdown+emoji
format:
  html:
    code-copy: hover
    link-external-icon: true
    link-external-newwindow: true
    email-obfuscation: javascript
#    embed-resources: true
    toc: true
    other-links:
      - text: Office Hours Zoom
        href: https://cofc.zoom.us/j/2805963064?pwd=CX8apjtmXACwaxLQ3NLeczxDHlUlpM.1
        target: _blank
        icon: chat-left-dots
    #  - text: Book an appointment
    #    href: https://outlook.office.com/bookwithme/user/0a4ce8c8942f4df4a1c6249a52630d7a@g.cofc.edu?anonymous&ep=plink
    #    target: _blank
    #    icon: calender-day
    #  - text: Book a zoom appointment
    #    href: https://outlook.office.com/bookwithme/user/0a4ce8c8942f4df4a1c6249a52630d7a@g.cofc.edu/meetingtype/_TR502DM80G5OpzXWWKlMw2?anonymous&ep=mlink
    #    target: _blank
    #    icon: calender-day
---

# Tuck Williamson, Graduate Teaching Assistant { .unnumbered .unlisted }

---

Graduate Student - Masters in Computer Science, College of Charleston

<!-- 
:::: { .callout-important }

Do not wait until the last minute to contact me for help! I have a family and my
own classes.

If you have not [made an appointment](#appointments) during my office hours or 
[requested an appointment](#requesting-help-outside-of-office-hours)
outside my regular office hours in advance there may be little I can do to 
help you on short notice.

I will not be hurt or upset if you **book early and then cancel when you don't need 
help**^[Please cancel if possible. There is a button in your 
calendar event to cancel to make it easy to do so.].
Book something then cancel instead of emailing me at the last minute please.

::::

# Links

**Just the important stuff conveniently collected.**

- [Message me.][email]{.external target="_blank"}
- [Book an appointment.]({{< meta booklink >}}){.external target="_blank"}
- [Book a zoom appointment.]({{< meta zoomlink >}}){.external target="_blank"}
- [Request a meeting outside of normal office hours.][reqOOOM]
 -->

# Contact Information

- **Email Me**: *williamson***th** (at) g (dot) cofc (dot) edu - 
- **Communicate via OAKS**: You can message me using OAKS via the 'Communicate' tab of the class.
- **Alternative**: you can use [this form to message me][email]{.external target="_blank"}
- **Zoom during Office Hours**: [open my zoom meeting.][zoomLink]{.external target="_blank"}

<!-- [email]: https://forms.office.com/Pages/ResponsePage.aspx?id=ONSF4rrbTEqUHFk7pCLerDUFZmClAphNkr9VpphUs0hURTFMVjlLWkdYTEk3QkxYRUxGTkE5NjM5Wi4u -->
[email]: https://docs.google.com/forms/d/e/1FAIpQLSfLkdXRgxcd-Y0421rsf8eSL7usSYazPWt39RCxtxPVBMG6kA/viewform?usp=header

<!--
[email]: mailto:williamsonth@cofc.edu?subject=Question%20about%20340
-->

<!--
**Office**: {{< meta office >}}
-->

# Office Hours

:::: { .callout-caution}

I am out of town for a family trip from **July 12** through **July 20**.
I will not be available at all during this time. 

::::

<!--
:::: { .callout-caution}

**Please check here prior to making a trip to my office.**

I **will** update my office hours here throughout the semester.
Specifically after the first couple of weeks when I have determined what works 
best for you, and for my classes/assignments.

::::

If you are already at Harbor Walk feel free to drop by during my office hours ({{< meta office >}}).

## Center for Student Learning Office Hours

I am working with the **[CSL](http://csl.cofc.edu/){.external target="_blank"}** to integrate some of my office 
hours with the tutoring desk at **Harbor Walk East** room **105F**. 

During the times listed below that are marked as **CSL** I will not be available
to zoom, but you are welcome to drop in at room **105F** to see me.
-->

## Current Office Hours Table


| Day       |                                           Hours | Exceptions |
|:----------|------------------------------------------------:|------------|
| Monday    |                       🌙 End of class - 9:30 pm | **Out of Office July 14** |
| Tuesday   |                                 🌙 8 pm - 10 pm | **Out of Office July 15** |
| Wednesday |               10am - noon                       | **Out of Office July 16** |
| Thursday  |               10am - noon <br> 2pm - 4pm        | **Out of Office July 17** <br> --- <br> **On July 24 from 3pm -4pm** |
| Friday - Sunday   |                **By appointment Only**  | **Out of Office July 18-20** |
: Office Hours (updated {{< meta date-modified >}} ) {.striped }

# Appointments

You don't need to book an appointment for office hours, but please e-mail me if it is during my posted hours and I don't immediately let you in to my zoom meeting.

<!-- You don't **need** to make an appointment for my office hours; however, I do have a 
family and may have things come up. 
If you know you want to see me then making an appointment will be helpful both in 
that if something comes up I know who I need to reschedule, and additionally I can 
get an idea of what you need to discuss. 
[Book an appointment]({{< meta booklink >}}){.external target="_blank"}.

I am happy to help out either in person or via zoom, but for zoom based help 
please make an appointment. 
Tuesday evening hours that are **Appointment Only** will be offered by zoom appointment. 
[Book a zoom appointment]({{< meta zoomlink >}}){.external target="_blank"}. 
 -->

## Requesting Help Outside of Office Hours

If my office hours are not compatible with your schedule please [message me and I will try and work something out.][email]{.external target="_blank"}
I will try and schedule time with you that works for both of our schedules.

<!-- [request a meeting
with me by filling out the linked form][reqOOOM].  -->


[reqOOOM]: https://forms.office.com/Pages/ResponsePage.aspx?id=ONSF4rrbTEqUHFk7pCLerDUFZmClAphNkr9VpphUs0hUNVJKTTZQSFUyRVRVVkZSUzdWTzRYNjYxNy4u {.external target="_blank"}

<!--
Providing me with **at least three** options that would work for your schedule 
would be **helpful**.
[reqOOOM]: mailto:williamsonth@cofc.edu?subject=Request%20for%20a%20meeting%20outside%20of%20office%20hours.&body=I%20want%20to%20request%20a%20meeting%20outside%20of%20your%20office%20hours.%0A%0AI%20would%20be%20able%20to%20meet%20the%20following%20times%3A%0A1%3A%20%0A2%3A%0A3%3A%0A%0AThank%20you%2C%0A%0AYOUR_NAME_HERE {.external target="_blank"}
-->

# Zoom Information

As this is a remote class all of my office hours will be zoom based and accessed using the information below.

<!--
I will also be available via zoom during my office hours. If you want to have an
unscheduled zoom session with me during office hours you can try my personal 
meeting room (details below). Please just 
[fill this out and I will get pinged with the request][reqZoomNow].

[reqZoomNow]: mailto:williamsonth@cofc.edu?subject=Would%20you%20be%20able%20to%20have%20a%20Zoom%20meeting%20Now%3F&body=Would%20you%20be%20able%20to%20zoom%20with%20me%20shortly%3F%0A%0AADD-DETAILS-HERE-IF-YOU-WANT%0A%0AThanks%2C%0A%0AYOUR_NAME_HERE
-->

[reqZoomNow]: https://forms.office.com/Pages/ResponsePage.aspx?id=ONSF4rrbTEqUHFk7pCLerDUFZmClAphNkr9VpphUs0hUQUQ4UTk0VTI1SVBSTlVDVTIxSjE4VUkwRy4u

<!-- 
:::: { .callout-warning }

If I do not accept you into my meeting I may be busy with another student via zoom
or in person.

In such an event please either book an appointment ([see above](#appointments)) or 
[email me][email] and I will get back to you as soon as I can.

::::
 -->

## Zoom Meeting Details
**Topic**: Tuck Williamson's Personal Meeting Room

[Join Zoom Meeting https://cofc.zoom.us/j/2805963064?pwd=CX8apjtmXACwaxLQ3NLeczxDHlUlpM.1][zoomLink]{.external target="_blank"}

[zoomLink]: https://cofc.zoom.us/j/2805963064?pwd=CX8apjtmXACwaxLQ3NLeczxDHlUlpM.1

```default
https://cofc.zoom.us/j/2805963064?pwd=CX8apjtmXACwaxLQ3NLeczxDHlUlpM.1
```

**Meeting ID**: 

```default
280 596 3064
```

**Passcode**: 

``` default
A1ZkH9
```

---

One tap mobile
[+13092053325,,2805963064# US](tel:+13092053325,,2805963064#)
[+13126266799,,2805963064# US (Chicago)](tel:+13126266799,,2805963064#)

---

Dial by your location

- [+1 309 205 3325 US](tel:+13092053325)
- [+1 312 626 6799 US (Chicago)](tel:+13126266799)
- [+1 646 558 8656 US (New York)](tel:+16465588656)
- [+1 646 931 3860 US](tel:+16469313860)
- [+1 301 715 8592 US (Washington DC)](tel:+13017158592)
- [+1 305 224 1968 US](tel:+13052241968)
- [+1 669 900 9128 US (San Jose)](tel:+16699009128)
- [+1 689 278 1000 US](tel:+16892781000)
- [+1 719 359 4580 US](tel:+17193594580)
- [+1 253 205 0468 US](tel:+12532050468)
- [+1 253 215 8782 US (Tacoma)](tel:+12532158782)
- [+1 346 248 7799 US (Houston)](tel:+13462487799)
- [+1 360 209 5623 US](tel:+13602095623)
- [+1 386 347 5053 US](tel:+13863475053)
- [+1 507 473 4847 US](tel:+15074734847)
- [+1 564 217 2000 US](tel:+15642172000)
- [+1 669 444 9171 US](tel:+16694449171)

Find your local number: <https://cofc.zoom.us/u/adSKwf1df4>

